schema: "classroom50/repo-config/v1"
classroom: "developing-the-interactive-web"
assignment: "lec-3"
secret: "coos6z1d"
owner:
  username: "winte928"
  id: 230185743
  accepted_at: "2026-09-15T13:18:32Z"
